id: P010458
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ1852
  title: བདེ་མཆོག་ཆོས་འབྱུང་
  author: ''
  volumes:
    0fa6eeec72c14f1cad90ed7519b50503:
      image_group_id: I1CZ1899
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
